name: 'Test coverage report'
description: 'Creates comment with test coverage report in the Pull Request'
inputs:
  htmlReports:
    description: "Comma separated paths of the jacoco html coverage pages"
    required: true
    default: '1000'
  paths:
    description: "Comma separated paths of the jacoco xml reports"
    required: true
  token:
    description: "Github personal token to add commits to Pull Request"
    required: true
  title:
    description: "Optional title for the Pull Request comment"
    required: false
    default: "Code coverage report"
  update-comment:
    description: "Update comment instead of creating new ones"
    required: false
    default: "false"
  debug:
    required: false
    default: "false"
runs:
  using: 'node16'
  main: 'dist/action.js'
