name: 'Test coverage report'
description: 'Creates comment with test coverage report in the Pull Request'
inputs:
  sourcePaths:
    description: "Comma separated paths of the sources"
    required: true
    default: '1000'
  paths:
    description: "Comma separated paths of the jacoco / kover xml reports"
    required: true
  masterPaths:
    description: "Comma separated paths of the jacoco / kover xml reports from Master (artefact)"
    required: false
    default: ""
  token:
    description: "Github personal token to add commits to Pull Request"
    required: false
    default: ${{github.token}}
  title:
    description: "Optional title for the Pull Request comment"
    required: false
    default: "Code coverage report"
  updateComment:
    description: "Update comment instead of creating new one"
    required: false
    default: "true"
  debug:
    required: false
    description: "log debug info"
    default: "false"
  repo:
    description: "Repository name with owner"
    required: false
    default: ${{github.repository}}
  artifactBranch:
    description: "Branch name"
    required: false
  artifactWorkflow:
    description: "Workflow name"
    required: false
  downloadPath:
    description: "Where to unpack the artifact"
    required: false
    default: "./"
  artifactName:
    description: "Artifact name"
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: "search"
  color: "blue"
